development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://teacher-note.herokuapp.com/faye"
  secret_token: "6760af1e77076b48b1537771ad59ff9c6e1a7db73207870c626129df4560c912"
  signature_expiration: 3600 # one hour
